package backtracking.a_subequence;

import java.util.ArrayList;
import java.util.List;

/**
 * https://www.youtube.com/watch?v=CqKyAIxAykA&list=PLICVjZ3X1AcY5ai7at5OvS4ckXiMbWxCa&index=3
 */

public class d_sub_seq_ps_loop_method_remove_duplicate {
    static void main() {
        SolutionD solution = new SolutionD();
        int[] numbers = {1, 2, 2, 2};
        System.out.println(solution.subsequence(numbers));
    }
}

class SolutionD {

    List<List<Integer>> subsequence(int[] numbers) {
        List<List<Integer>> result = new ArrayList<>();
        List<Integer> temp = new ArrayList<>();
        int startIdx = 0;
        backtrack(numbers, result, temp, startIdx);
        return result;
    }

    private void backtrack(int[] numbers, List<List<Integer>> result, List<Integer> temp, int idx) {
        result.add(new ArrayList<>(temp));
        //Loop
        for (int i = idx; i < numbers.length; i++) {
            // How we reach here, in 2nd branch after removeLast
            if (i != idx /* here I should not be starting point of exploration*/
                    &&
                    numbers[i] == numbers[i - 1] /* previous number should not be explored*/
            ) {
                continue;
            }
            //
            temp.addLast(numbers[i]);
            backtrack(numbers, result, temp, i + 1);
            // below should not be called if covered backward
            temp.removeLast();
        }
    }
}
/**
 * [
 * [1], [1, 2], [1, 2, 2], [1, 2, 2, 2],
 * -> [1, 2, 2], --> duplicate [generated by exploring temp.removeLast() in Loop]
 * -> [1, 2], --> duplicate
 * -> [1, 2, 2], --> duplicate
 * -> [1, 2], --> duplicate -> i need to look back and stop where i dont see duplicate
 * [2], [2, 2], [2, 2, 2],
 * -> [2, 2], --> duplicate
 * -> [2], --> duplicate
 * -> [2, 2], --> duplicate
 * -> [2] --> duplicate
 * ]
 */